version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ message broker
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: kafka:9092 # Connect to Kafka broker
      JVM_OPTS: "-Xms32M -Xmx64M"
    restart: always

  messaging-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    container_name: messaging-service
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      KAFKA_BROKERS: kafka:9092
      KAFKA_GROUP_ID: messaging-group
    depends_on:
      - rabbitmq
      - kafka

networks:
  default:
    driver: bridge